Repository NeowayLabs/goss-cis-benchmark, pull requests merged in 2018-10, with the labels that each got.

#5 Improve Section 02
  test_section_02_level1.yml
Labels: bug, enhancement

#3 Add tests to check CIS section 6.1
  scripts/test_section_06_level1/6-2-10.sh
  scripts/test_section_06_level1/6-2-11.sh
  scripts/test_section_06_level1/6-2-12.sh
  scripts/test_section_06_level1/6-2-13.sh
  scripts/test_section_06_level1/6-2-14.sh
  scripts/test_section_06_level1/6-2-15.sh
  scripts/test_section_06_level1/6-2-16.sh
  scripts/test_section_06_level1/6-2-17.sh
  scripts/test_section_06_level1/6-2-18.sh
  scripts/test_section_06_level1/6-2-19.sh
  scripts/test_section_06_level1/6-2-6.sh
  scripts/test_section_06_level1/6-2-7.sh
  scripts/test_section_06_level1/6-2-8.sh
  scripts/test_section_06_level1/6-2-9.sh
  test_section_06_level1.yml
Labels: enhancement

#4 Add section01
  test_section_01_level1.yml
Labels: enhancement

#10 Enable yamllint strict mode
  .travis.yml
  test_section_06_level1.yml
Labels: bug

#11 Ensure unmounting insecure filesystems and small improvements
  test_section_01_level1.yml
Labels: bug, enhancement

#12 Fix section 06 - absolute script paths
  test_section_06_level1.yml
Labels: bug
